
from objects import visual

class win32_colors():
	__slots__ = ['used', 'scrollbar', 'background', 'activetitle', 'inactivetitle', 'menu', 'window', 'windowframe', 'menutext', 'windowtext', 'titletext', 'activeborder', 'inactiveborder', 'appworkspace', 'hilight', 'hilighttext', 'buttonface', 'buttonshadow', 'graytext', 'buttontext', 'inactivetitletext', 'buttonhilight', 'buttondkshadow', 'buttonlight', 'infotext', 'infowindow', 'buttonalternateface', 'hottrackingcolor', 'gradientactivetitle', 'gradientinactivetitle', 'menuhilight', 'menubar']

	def __init__(self):
		self.scrollbar = visual.visual_color()
		self.background = visual.visual_color()
		self.activetitle = visual.visual_color()
		self.inactivetitle = visual.visual_color()
		self.menu = visual.visual_color()
		self.window = visual.visual_color()
		self.windowframe = visual.visual_color()
		self.menutext = visual.visual_color()
		self.windowtext = visual.visual_color()
		self.titletext = visual.visual_color()
		self.activeborder = visual.visual_color()
		self.inactiveborder = visual.visual_color()
		self.appworkspace = visual.visual_color()
		self.hilight = visual.visual_color()
		self.hilighttext = visual.visual_color()
		self.buttonface = visual.visual_color()
		self.buttonshadow = visual.visual_color()
		self.graytext = visual.visual_color()
		self.buttontext = visual.visual_color()
		self.inactivetitletext = visual.visual_color()
		self.buttonhilight = visual.visual_color()
		self.buttondkshadow = visual.visual_color()
		self.buttonlight = visual.visual_color()
		self.infotext = visual.visual_color()
		self.infowindow = visual.visual_color()
		self.buttonalternateface = visual.visual_color()
		self.hottrackingcolor = visual.visual_color()
		self.gradientactivetitle = visual.visual_color()
		self.gradientinactivetitle = visual.visual_color()
		self.menuhilight = visual.visual_color()
		self.menubar = visual.visual_color()

		self.scrollbar.set_int([200,200,200])
		self.background.set_int([59,110,165])
		self.activetitle.set_int([153,180,209])
		self.inactivetitle.set_int([191,205,219])
		self.menu.set_int([240,240,240])
		self.window.set_int([255,255,255])
		self.windowframe.set_int([100,100,100])
		self.menutext.set_int([0,0,0])
		self.windowtext.set_int([0,0,0])
		self.titletext.set_int([0,0,0])
		self.activeborder.set_int([180,180,180])
		self.inactiveborder.set_int([244,247,252])
		self.appworkspace.set_int([171,171,171])
		self.hilight.set_int([0,120,215])
		self.hilighttext.set_int([255,255,255])
		self.buttonface.set_int([240,240,240])
		self.buttonshadow.set_int([160,160,160])
		self.graytext.set_int([109,109,109])
		self.buttontext.set_int([0,0,0])
		self.inactivetitletext.set_int([0,0,0])
		self.buttonhilight.set_int([255,255,255])
		self.buttondkshadow.set_int([105,105,105])
		self.buttonlight.set_int([227,227,227])
		self.infotext.set_int([0,0,0])
		self.infowindow.set_int([255,255,225])
		self.buttonalternateface.set_int([0,0,0])
		self.hottrackingcolor.set_int([0,102,204])
		self.gradientactivetitle.set_int([185,209,234])
		self.gradientinactivetitle.set_int([215,228,242])
		self.menuhilight.set_int([0,120,215])
		self.menubar.set_int([240,240,240])

	def set(self, c, v):
		if v:
			self.used = True
			match c.lower():
				case 'scrollbar': self.scrollbar.set_int(v)
				case 'background': self.background.set_int(v)
				case 'activetitle': self.activetitle.set_int(v)
				case 'inactivetitle': self.inactivetitle.set_int(v)
				case 'menu': self.menu.set_int(v)
				case 'window': self.window.set_int(v)
				case 'windowframe': self.windowframe.set_int(v)
				case 'menutext': self.menutext.set_int(v)
				case 'windowtext': self.windowtext.set_int(v)
				case 'titletext': self.titletext.set_int(v)
				case 'activeborder': self.activeborder.set_int(v)
				case 'inactiveborder': self.inactiveborder.set_int(v)
				case 'appworkspace': self.appworkspace.set_int(v)
				case 'hilight': self.hilight.set_int(v)
				case 'hilighttext': self.hilighttext.set_int(v)
				case 'buttonface': self.buttonface.set_int(v)
				case 'buttonshadow': self.buttonshadow.set_int(v)
				case 'graytext': self.graytext.set_int(v)
				case 'buttontext': self.buttontext.set_int(v)
				case 'inactivetitletext': self.inactivetitletext.set_int(v)
				case 'buttonhilight': self.buttonhilight.set_int(v)
				case 'buttondkshadow': self.buttondkshadow.set_int(v)
				case 'buttonlight': self.buttonlight.set_int(v)
				case 'infotext': self.infotext.set_int(v)
				case 'infowindow': self.infowindow.set_int(v)
				case 'buttonalternateface': self.buttonalternateface.set_int(v)
				case 'hottrackingcolor': self.hottrackingcolor.set_int(v)
				case 'gradientactivetitle': self.gradientactivetitle.set_int(v)
				case 'gradientinactivetitle': self.gradientinactivetitle.set_int(v)
				case 'menuhilight': self.menuhilight.set_int(v)
				case 'menubar': self.menubar.set_int(v)
				case _: print('unknown color type', c)
